services:
  srd:
    build: .
    stdin_open: true
    tty: true
    entrypoint: /bin/sh
    volumes:
      - "./:/usr/src/suspicious-reading-detector"
      - "./data:/usr/src/suspicious-reading-detector/data:ro"