name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies & test
        run: |
          ls && ./composer.phar install \
          && ls vendor/autoload.php \
          && vendor/bin/phpunit -c phpunit.xml --bootstrap vendor/autoload.php
