name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies & test
        run: ls && ./composer.phar install && vendor/bin/phpunit -c phpunit.xml
